spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reportsuspect
    username: root
    password:
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reportsuspect
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/reportsuspect

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql